services:
  tiny-nav:
    image: hanxi/tiny-nav
    container_name: tiny-nav
    restart: unless-stopped
    ports:
      - 8080:58080
    environment:
      NAV_USERNAME: admin
      NAV_PASSWORD: 123456
    volumes:
      - /tiny-nav-data:/app/data
